const categories=['Fiction','Mystery','Romance','Fantasy','Sequential Art','Historical Fiction','Poetry','History','Science','Young Adult','Nonfiction','Travel','Music','Business','Food and Drink'];
const titleA=['A Light in the Attic','Tipping the Velvet','Soumission','Sharp Objects','Sapiens: A Brief History','The Silent Patient','The Midnight Library','Atomic Habits','The Book Thief','The Alchemist','Educated','Circe','Dune','Normal People','The Song of Achilles','The Goldfinch','Little Women','The Night Circus','The Martian','Becoming'];
function sampleData(){const rows=[];const categoryFor=i=>i<226?'Fiction':i<350?'Mystery':i<468?'Romance':i<561?'Fantasy':i<637?'Sequential Art':categories[(i*11)%categories.length];const ratingFor=i=>i<60?1:i<200?2:i<440?3:i<780?4:5;for(let i=0;i<1000;i++){const price=+(5.10+(i*17%58)+(i%9)*.37).toFixed(2);rows.push({title:i<20?titleA[i]:`${titleA[i%20]} — Edition ${Math.floor(i/20)+1}`,category:categoryFor(i),rating:ratingFor(i),price,availability:'In Stock',upc:`BOOK-${String(i+1).padStart(4,'0')}`,source_url:`https://books.toscrape.com/catalogue/page-${Math.floor(i/20)+1}.html`})}return rows}
const allBooks=(Array.isArray(window.BOOK_DATA)&&window.BOOK_DATA.length?window.BOOK_DATA:sampleData()).map((b,i)=>({...b,price:+b.price,rating:+b.rating,availability:b.availability||'In Stock',source_url:b.source_url||'https://books.toscrape.com/'}));
const el=id=>document.getElementById(id);let currentPage=1;const pageSize=10;let filtered=[];
const categoryFilter=el('categoryFilter');[...new Set(allBooks.map(b=>b.category))].sort().forEach(c=>categoryFilter.add(new Option(c,c)));
function applyFilters(){const cat=categoryFilter.value,rate=el('ratingFilter').value,pr=el('priceFilter').value,q=el('searchInput').value.trim().toLowerCase();filtered=allBooks.filter(b=>{const priceOk=pr==='all'||(()=>{const [a,z]=pr.split('-').map(Number);return b.price>=a&&b.price<z})();return(cat==='all'||b.category===cat)&&(rate==='all'||b.rating===+rate)&&priceOk&&(!q||`${b.title} ${b.category}`.toLowerCase().includes(q))});currentPage=1;render()}
function render(){const count=filtered.length,avg=count?filtered.reduce((s,b)=>s+b.price,0)/count:0,inStock=filtered.filter(b=>/stock/i.test(b.availability)).length;el('bookCount').textContent=count.toLocaleString();el('pageCount').textContent=Math.ceil(count/20).toLocaleString();el('averagePrice').textContent=`£${avg.toFixed(2)}`;el('coverage').textContent=`${Math.round(count/allBooks.length*100)}%`;el('donutTotal').textContent=`${count.toLocaleString()} Books`;el('stockPercent').textContent=count?`${Math.round(inStock/count*100)}% of books available`:'No matching books';el('stockNote').textContent=count?`${inStock.toLocaleString()} matching books are currently in stock.`:'Change a filter to see catalogue records.';renderPrice();renderCategories();renderRatings();renderTable()}
function renderPrice(){const bins=[{l:'£0–£10',a:0,z:10},{l:'£10–£20',a:10,z:20},{l:'£20–£30',a:20,z:30},{l:'£30–£40',a:30,z:40},{l:'£40–£50',a:40,z:50},{l:'£50–£60',a:50,z:60},{l:'£60+',a:60,z:999}],vals=bins.map(x=>filtered.filter(b=>b.price>=x.a&&b.price<x.z).length),max=Math.max(1,...vals);el('priceChart').innerHTML=bins.map((x,i)=>`<div class="vbar-wrap"><b>${vals[i]}</b><div class="vbar" style="height:${Math.max(2,vals[i]/max*92)}%"></div><small>${x.l}</small></div>`).join('')}
function renderCategories(){const counts={};filtered.forEach(b=>counts[b.category]=(counts[b.category]||0)+1);const top=Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,5),max=Math.max(1,...top.map(x=>x[1]));el('categoryChart').innerHTML=top.length?top.map(([name,n])=>`<div class="hrow"><span title="${escapeHtml(name)}">${escapeHtml(name)}</span><div class="track"><div class="fill" style="width:${n/max*100}%"></div></div><b>${n}</b></div>`).join(''):'<p>No matching categories.</p>'}
function renderRatings(){const colors=['#ff5d68','#ff9335','#ffd23f','#3389f3','#39bd73'],counts=[1,2,3,4,5].map(r=>filtered.filter(b=>b.rating===r).length),total=Math.max(1,filtered.length);let acc=0;const stops=[];counts.forEach((n,i)=>{const start=acc;acc+=n/total*100;stops.push(`${colors[i]} ${start}% ${acc}%`)});el('ratingDonut').style.background=`conic-gradient(${stops.join(',')})`;el('ratingLegend').innerHTML=counts.map((n,i)=>`<span><i style="background:${colors[i]}"></i>${i+1} Star (${n})</span>`).join('')}
function renderTable(){const pages=Math.max(1,Math.ceil(filtered.length/pageSize));if(currentPage>pages)currentPage=pages;const start=(currentPage-1)*pageSize,rows=filtered.slice(start,start+pageSize);el('bookTable').innerHTML=rows.length?rows.map((b,i)=>`<tr><td>${start+i+1}</td><td>${escapeHtml(b.title)}</td><td>${escapeHtml(b.category)}</td><td><span class="stars">${'★'.repeat(b.rating)}</span>${'☆'.repeat(5-b.rating)}</td><td>£${b.price.toFixed(2)}</td><td><span class="status">${escapeHtml(b.availability)}</span></td><td><a class="source-link" href="${b.source_url}" target="_blank" rel="noopener">View ↗</a></td></tr>`).join(''):'<tr><td colspan="7">No matching records.</td></tr>';el('recordSummary').textContent=filtered.length?`Showing ${start+1}–${Math.min(start+pageSize,filtered.length)} of ${filtered.length.toLocaleString()}`:'0 matching records';el('pageLabel').textContent=`Page ${currentPage} of ${pages}`;el('prevPage').disabled=currentPage===1;el('nextPage').disabled=currentPage===pages}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function downloadCSV(){const headers=['title','category','rating','price','availability','upc','source_url'];const csv=[headers.join(','),...filtered.map(b=>headers.map(h=>`"${String(b[h]??'').replaceAll('"','""')}"`).join(','))].join('\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='filtered_book_catalogue.csv';a.click();URL.revokeObjectURL(url)}
[categoryFilter,el('ratingFilter'),el('priceFilter')].forEach(x=>x.addEventListener('change',applyFilters));el('searchInput').addEventListener('input',applyFilters);el('prevPage').addEventListener('click',()=>{if(currentPage>1){currentPage--;renderTable()}});el('nextPage').addEventListener('click',()=>{if(currentPage<Math.ceil(filtered.length/pageSize)){currentPage++;renderTable()}});el('downloadBtn').addEventListener('click',downloadCSV);filtered=[...allBooks];render();
